global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'ayushahirwar1999@gmail.com'
  smtp_auth_username: ayushahirwar1999@gmail.com
  smtp_auth_password: ajmu drgf wefs wcjx  # Use an App Password if 2FA is enabled
  smtp_require_tls: true


route:
  receiver: 'gmail-notifications'

receivers:
  - name: 'gmail-notifications'
    email_configs:
      - to: ayushahirwar1999@gmail.com
        send_resolved: true
