global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'flask-app'
    static_configs:
      - targets: ['app:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
