---
- name: Restart the Flask app Docker container
  hosts: localhost
  become: false
  tasks:
    - name: Restart container named "infra-guardian-app-1"
      community.docker.docker_container:
        name: infra-guardian-app-1
        state: started
        restart: true
